UBER_CLIENT_ID: 'TsMHMvYogJlGE2CYSjiR7lmhrL0Z0y_n'
UBER_CLIENT_SECRET: '7KYxLBMCaHKP_diVqedXMqP6OF3OOI1WauyioDcH'
UBER_SERVER_TOKEN: 'QySDXaeFhcHVEcHAQwRaErL860SZBo819-qR-vng'

LYFT_CLIENT_ID: 'bt2nhYsFgB_9'
LYFT_CLIENT_SECRET: 'waumLg4k1uy6GIseVwe96UiLJPzUYC8-'
LYFT_CLIENT_TOKEN: 'gAAAAABY3Vxp97zF4q1hMvzaER0N_P5IhzR28cssA39BJP1M3IUeetkVL9XeykhdWfwXIgYaO_IHeevEltK1D0gaxBwMSzFUpjZEx3iI8aHSM4z2AlSuOGAiAZTRc0G6NvFoge43BNxFUwC9m2UiuoNGiDYAkFfH1-_woD4RPFV7C-dnX7qXHNQ='
